// src/pages/Viewer.tsx
import { useState } from 'react';
import { datasource, ViewerComponent } from '../config';
import { List } from '../components/List';
import { DatePicker } from '../components/DatePicker';

export const Viewer = () => {
  const recipients = datasource.retrieveBucketListFromStorage();
  const [recipient, select_recipient] = useState('alejandro_1701@hotmail.com');

  const [date, select_date] = useState(new Date('2008-11-06'));
  const logs = datasource.retrieveBucketFromStorage(recipient, {
    year: date.getFullYear(),
    month: date.getMonth() + 1,
    day: date.getDate() + 1,
  });

  return (
    <>
      <h1>This is the chat history page</h1>
      <List
        items={recipients}
        selected_item={recipient}
        select_item={select_recipient}
      />
      <DatePicker date={date} select_date={select_date} />
      <ViewerComponent logs={logs} />
    </>
  );
};

// src/views/Viewer.vue
<template>
  <div>This is the chat history page</div>
  <v-date-picker v-model="date" />
  <component :is="AsyncViewerComponent" :logs="logs" />
</template>

<script>
  import { defineAsyncComponent } from "@vue/runtime-core";
  const date = new Date("2008-11-06");

  export default {
    name: "Viewer",
    data() {
      return { sender: "duvly@hotmail.com", date };
    },
    computed: {
      logs() {
        const logs = this.$datasource.retrieveBucketFromStorage(this.sender, {
          year: this.date.getFullYear(),
          month: this.date.getMonth() + 1,
          day: this.date.getDate() + 1,
        });
        return logs;
      },
      AsyncViewerComponent() {
        return defineAsyncComponent(() =>
          import(`../components/viewer/${this.$viewerComponent}.vue`)
        );
      },
    },
  };
</script>

<style>
  #messages {
    white-space: pre-line;
    text-align: left;
  }
</style>
