// src/components/List.tsx
export const List = ({ selected_item, items, select_item }) => {
  return (
    <ul>
      {items.map((item) => (
        <li
          key={item}
          onClick={select_item(item)}
          className={item === selected_item ? 'text-red-500' : ''}
        >
          {item}
        </li>
      ))}
    </ul>
  );
};

// src/components/ListComponent.vue
<template>
  <ul>
    <li
      v-for="item in items"
      :key="item"
      @click="$emit('update:selectedItem', item)"
      :class="{ 'text-red-500': item === selectedItem }"
    >
      {{ item }}
    </li>
  </ul>
</template>

<script lang="ts">
  import { Options, Vue } from "vue-class-component";

  @Options({
    props: {
      items: Array,
      selectedItem: String,
    },
  })
  export default class ListComponent extends Vue {
    items!: Array<any>;
    selectedItem: string;
  }
</script>
